# Generated by Django 5.2.8 on 2025-12-06 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=255, verbose_name='Pregunta')),
                ('fecha_cierre', models.DateTimeField(db_index=True, verbose_name='Fecha de cierre')),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
            ],
            options={
                'verbose_name': 'Votación',
                'verbose_name_plural': 'Votaciones',
                'ordering': ['-fecha_cierre', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=150, verbose_name='Texto de la opción')),
                ('votacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='votaciones.votacion', verbose_name='Votación')),
            ],
            options={
                'verbose_name': 'Opción',
                'verbose_name_plural': 'Opciones',
            },
        ),
        migrations.CreateModel(
            name='LogIntentoVoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fue_exitoso', models.BooleanField(default=False, verbose_name='¿Fue exitoso?')),
                ('motivo_fallo', models.CharField(blank=True, max_length=255, verbose_name='Motivo del fallo')),
                ('origen', models.CharField(choices=[('APP_MOVIL', 'App móvil'), ('WEB', 'Sitio web')], default='APP_MOVIL', max_length=20, verbose_name='Origen')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_intentos_voto', to=settings.AUTH_USER_MODEL, verbose_name='Vecino')),
                ('votacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_intentos', to='votaciones.votacion', verbose_name='Votación')),
            ],
            options={
                'verbose_name': 'Log de intento de voto',
                'verbose_name_plural': 'Logs de intentos de voto',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_voto', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Hash del voto')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='votaciones.opcion', verbose_name='Opción')),
                ('votante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vecino')),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Votos',
            },
        ),
        migrations.AddIndex(
            model_name='votacion',
            index=models.Index(fields=['activa', 'fecha_cierre'], name='votaciones__activa_d4deec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='voto',
            unique_together={('opcion', 'votante')},
        ),
    ]
