# Generated by Django 5.0.8 on 2025-11-02 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votacion',
            options={'ordering': ['-fecha_cierre', '-id'], 'verbose_name': 'Votación', 'verbose_name_plural': 'Votaciones'},
        ),
        migrations.AlterField(
            model_name='votacion',
            name='activa',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='votacion',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creada por'),
        ),
        migrations.AlterField(
            model_name='votacion',
            name='fecha_cierre',
            field=models.DateTimeField(db_index=True, verbose_name='Fecha de cierre'),
        ),
        migrations.AddIndex(
            model_name='votacion',
            index=models.Index(fields=['activa', 'fecha_cierre'], name='votaciones__activa_d4deec_idx'),
        ),
    ]
