# Generated by Django 5.2.8 on 2025-12-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0002_alter_votacion_options_alter_votacion_activa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='hash_voto',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
