# Generated by Django 5.0.8 on 2025-08-16 22:59

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='rut',
            field=models.CharField(default='1233', help_text='Ej: 12345678-9 o 12.345.678-9', max_length=12, unique=True, validators=[core.validators.validar_rut]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
