# Generated by Django 5.0.8 on 2025-08-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfil_rut_alter_perfil_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['usuario__username'], 'verbose_name': 'perfil', 'verbose_name_plural': 'perfiles'},
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('directiva', 'Miembro Directiva'), ('vecino', 'Vecino')], default='vecino', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rut',
            field=models.CharField(help_text='Ej: 12345678-9', max_length=12, unique=True),
        ),
    ]
