# Generated by Django 5.0.8 on 2025-08-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_perfil_options_alter_perfil_rol_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={},
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rut',
            field=models.CharField(help_text='12345678-9', max_length=12, unique=True),
        ),
    ]
