# Generated by Django 5.2.5 on 2025-08-23 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_perfil_options_alter_perfil_rut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        # (tus otras operaciones…)
        migrations.AddConstraint(
            model_name='perfil',
            constraint=models.CheckConstraint(
                check=~models.Q(rut=''),
                name='rut_not_empty',
            ),
        ),
    ]