# Generated by Django 5.0.8 on 2025-08-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_perfil_rol_perfil_rut_not_empty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('presidente', 'PRESIDENTE'), ('secretaria', 'SECRETARIA'), ('tesorero', 'TESORERO'), ('suplente', 'SUPLENTE'), ('vecino', 'VECINO')], default='vecino', max_length=20),
        ),
    ]
