# Generated by Django 5.0.8 on 2025-10-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_perfil_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('presidente', 'PRESIDENTE'), ('secretaria', 'SECRETARIA'), ('tesorero', 'TESORERO'), ('suplente', 'SUPLENTE')], max_length=20),
        ),
    ]
