# Generated by Django 5.0.8 on 2025-11-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_perfil_apellido_materno_perfil_apellido_paterno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('presidente', 'PRESIDENTE'), ('secretaria', 'SECRETARIA'), ('tesorero', 'TESORERO'), ('suplente', 'SUPLENTE'), ('vecino', 'VECINO')], max_length=20),
        ),
    ]
