# Generated by Django 5.2.8 on 2025-11-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_perfil_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='direccion',
            field=models.CharField(default='', max_length=255, verbose_name='Dirección Completa'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='total_ninos',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de Niños (< 18 años)'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='total_residentes',
            field=models.PositiveIntegerField(default=1, verbose_name='Total de Residentes'),
        ),
    ]
