# Generated by Django 5.2.8 on 2025-11-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_perfil_direccion_perfil_total_ninos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token FCM'),
        ),
    ]
