# Generated by Django 5.2.8 on 2025-11-18 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_perfil_mfa_code_perfil_mfa_expires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='mfa_code',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='mfa_expires',
        ),
    ]
