# Generated by Django 5.2.8 on 2025-11-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_perfil_mfa_code_remove_perfil_mfa_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='mfa_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='mfa_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
