# Generated by Django 5.2.8 on 2025-11-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_perfil_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False, verbose_name='Debe cambiar contraseña'),
        ),
    ]
