# Generated by Django 5.2.8 on 2025-11-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_perfil_debe_cambiar_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='recovery_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='recovery_code_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
