# Generated by Django 5.2.8 on 2025-12-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_perfil_recovery_code_perfil_recovery_code_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='numero_casa',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='N° Casa/Depto/Lote'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='direccion',
            field=models.CharField(default='', max_length=255, verbose_name='Nombre de la Calle/Pasaje'),
        ),
    ]
