# Generated by Django 5.2.7 on 2025-11-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taller',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
