# Generated by Django 5.2.8 on 2025-11-17 16:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0002_taller_fecha_inicio_taller_fecha_termino'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taller',
            options={'ordering': ['fecha_inicio'], 'verbose_name': 'Taller', 'verbose_name_plural': 'Talleres'},
        ),
        migrations.AddField(
            model_name='taller',
            name='creado_el',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taller',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talleres_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taller',
            name='estado',
            field=models.CharField(choices=[('PROGRAMADO', 'Programado'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='taller',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Cancelación'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='cupos_totales',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='taller',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Inicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taller',
            name='fecha_termino',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Término'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taller',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
