# Generated by Django 5.2.8 on 2025-11-16 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimActa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acta_id_oltp', models.IntegerField(help_text="ID original de la app 'reuniones.Acta'", unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('fecha_reunion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DimTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taller_id_oltp', models.IntegerField(help_text="ID original de la app 'talleres'", unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('cupos_totales', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DimVecino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vecino_id_oltp', models.IntegerField(help_text='ID original del modelo User de Django', unique=True)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('rango_etario', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_sector', models.CharField(blank=True, max_length=255, null=True)),
                ('tiene_niños', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DimVotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votacion_id_oltp', models.IntegerField(help_text="ID original de la app 'votaciones'", unique=True)),
                ('pregunta', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FactConsultaActa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateTimeField()),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamart.dimacta')),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamart.dimvecino')),
            ],
        ),
        migrations.CreateModel(
            name='FactInscripcionTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField()),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamart.dimtaller')),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='datamart.dimvecino')),
            ],
        ),
        migrations.CreateModel(
            name='FactParticipacionVotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_voto', models.DateTimeField()),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamart.dimvecino')),
                ('votacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamart.dimvotacion')),
            ],
        ),
    ]
