# Generated by Django 5.2.8 on 2025-11-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactCalidadTranscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('total_palabras', models.PositiveIntegerField(default=0)),
                ('palabras_correctas', models.PositiveIntegerField(default=0)),
                ('precision_porcentaje', models.FloatField(help_text='Porcentaje de precisión (0–100)')),
                ('origen', models.CharField(blank=True, help_text='Origen de la transcripción: acta, reunión, etc.', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Calidad de Transcripción',
                'verbose_name_plural': 'Calidad de Transcripción',
                'ordering': ['fecha', 'origen'],
            },
        ),
    ]
