# Generated by Django 5.2.8 on 2025-12-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamart', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dimacta',
            index=models.Index(fields=['fecha_reunion'], name='datamart_di_fecha_r_b35e08_idx'),
        ),
        migrations.AddIndex(
            model_name='dimreunion',
            index=models.Index(fields=['fecha'], name='datamart_di_fecha_5ce7fb_idx'),
        ),
        migrations.AddIndex(
            model_name='dimvotacion',
            index=models.Index(fields=['fecha_inicio'], name='datamart_di_fecha_i_7ed59c_idx'),
        ),
        migrations.AddIndex(
            model_name='factasistenciareunion',
            index=models.Index(fields=['reunion'], name='datamart_fa_reunion_ec38cf_idx'),
        ),
        migrations.AddIndex(
            model_name='factasistenciareunion',
            index=models.Index(fields=['vecino'], name='datamart_fa_vecino__219f02_idx'),
        ),
        migrations.AddIndex(
            model_name='factcalidadtranscripcion',
            index=models.Index(fields=['fecha'], name='datamart_fa_fecha_cf7a6a_idx'),
        ),
        migrations.AddIndex(
            model_name='factcalidadtranscripcion',
            index=models.Index(fields=['origen', 'fecha'], name='datamart_fa_origen_ddf277_idx'),
        ),
        migrations.AddIndex(
            model_name='factconsultaacta',
            index=models.Index(fields=['fecha_consulta'], name='datamart_fa_fecha_c_4c790c_idx'),
        ),
        migrations.AddIndex(
            model_name='factconsultaacta',
            index=models.Index(fields=['acta', 'fecha_consulta'], name='datamart_fa_acta_id_49423e_idx'),
        ),
        migrations.AddIndex(
            model_name='factconsultaacta',
            index=models.Index(fields=['vecino', 'fecha_consulta'], name='datamart_fa_vecino__32b684_idx'),
        ),
        migrations.AddIndex(
            model_name='factinscripciontaller',
            index=models.Index(fields=['fecha_inscripcion'], name='datamart_fa_fecha_i_baba23_idx'),
        ),
        migrations.AddIndex(
            model_name='factinscripciontaller',
            index=models.Index(fields=['taller', 'fecha_inscripcion'], name='datamart_fa_taller__5f768d_idx'),
        ),
        migrations.AddIndex(
            model_name='factinscripciontaller',
            index=models.Index(fields=['vecino', 'fecha_inscripcion'], name='datamart_fa_vecino__052f19_idx'),
        ),
        migrations.AddIndex(
            model_name='factmetricasdiarias',
            index=models.Index(fields=['fecha'], name='datamart_fa_fecha_c3be51_idx'),
        ),
        migrations.AddIndex(
            model_name='factmetricastecnicas',
            index=models.Index(fields=['fecha'], name='datamart_fa_fecha_0dbe92_idx'),
        ),
        migrations.AddIndex(
            model_name='factparticipacionvotacion',
            index=models.Index(fields=['fecha_voto'], name='datamart_fa_fecha_v_d6b7cd_idx'),
        ),
        migrations.AddIndex(
            model_name='factparticipacionvotacion',
            index=models.Index(fields=['votacion', 'fecha_voto'], name='datamart_fa_votacio_b7e373_idx'),
        ),
        migrations.AddIndex(
            model_name='factparticipacionvotacion',
            index=models.Index(fields=['vecino', 'fecha_voto'], name='datamart_fa_vecino__8639d4_idx'),
        ),
        migrations.AddIndex(
            model_name='logrendimiento',
            index=models.Index(fields=['fecha'], name='datamart_lo_fecha_26529c_idx'),
        ),
        migrations.AddIndex(
            model_name='logrendimiento',
            index=models.Index(fields=['fecha', 'path'], name='datamart_lo_fecha_2326ec_idx'),
        ),
        migrations.AddIndex(
            model_name='logrendimiento',
            index=models.Index(fields=['fecha', 'status_code'], name='datamart_lo_fecha_08c52a_idx'),
        ),
        migrations.AddIndex(
            model_name='logrendimiento',
            index=models.Index(fields=['path'], name='datamart_lo_path_fbee2c_idx'),
        ),
    ]
