# Generated by Django 5.2.8 on 2025-11-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamart', '0002_factcalidadtranscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactAsistenciaReunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reunion_id_oltp', models.IntegerField()),
                ('fecha_reunion', models.DateField()),
                ('total_presentes', models.IntegerField(default=0)),
            ],
        ),
    ]
