# Generated by Django 5.0.8 on 2025-08-30 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('tipo', models.CharField(choices=[('Ordinaria', 'Ordinaria'), ('Extraordinaria', 'Extraordinaria')], default='Ordinaria', max_length=20)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('tabla', models.TextField(verbose_name='Tabla de contenidos')),
                ('creada_el', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reuniones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('reunion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reuniones.reunion')),
                ('contenido', models.TextField(verbose_name='Contenido del Acta')),
                ('aprobada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistentes', to='reuniones.reunion')),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('reunion', 'vecino')},
            },
        ),
    ]
