# Generated by Django 5.2.8 on 2025-12-17 01:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='aprobada',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='acta',
            name='archivo_audio',
            field=models.FileField(blank=True, null=True, upload_to='audios_reuniones/'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='calificacion_precision',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='acta',
            name='estado_transcripcion',
            field=models.CharField(choices=[('NO_SUBIDO', 'No Subido'), ('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], db_index=True, default='NO_SUBIDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='presente',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='logconsultaacta',
            name='fecha_consulta',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='estado',
            field=models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_CURSO', 'En Curso'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], db_index=True, default='PROGRAMADA', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='fecha',
            field=models.DateTimeField(db_index=True, verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='tipo',
            field=models.CharField(choices=[('Ordinaria', 'Ordinaria'), ('Extraordinaria', 'Extraordinaria')], db_index=True, default='Ordinaria', max_length=20),
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['reunion', 'presente'], name='reuniones_a_reunion_e5fd09_idx'),
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['vecino', 'presente'], name='reuniones_a_vecino__389533_idx'),
        ),
        migrations.AddIndex(
            model_name='logconsultaacta',
            index=models.Index(fields=['acta', 'fecha_consulta'], name='reuniones_l_acta_id_3dd2a6_idx'),
        ),
        migrations.AddIndex(
            model_name='logconsultaacta',
            index=models.Index(fields=['vecino', 'fecha_consulta'], name='reuniones_l_vecino__fcaf00_idx'),
        ),
        migrations.AddIndex(
            model_name='reunion',
            index=models.Index(fields=['estado', 'fecha'], name='reuniones_r_estado_918e77_idx'),
        ),
        migrations.AddIndex(
            model_name='reunion',
            index=models.Index(fields=['fecha'], name='reuniones_r_fecha_587727_idx'),
        ),
    ]
