# Generated by Django 5.0.8 on 2025-10-31 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='aprobada',
            field=models.BooleanField(default=True),
        ),
    ]
