# Generated by Django 5.2.8 on 2025-11-10 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0003_alter_acta_aprobada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='aprobado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acta',
            name='transcripcion_actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='transcripcion_borrador',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='acta',
            name='transcripcion_estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADA', 'Aprobada')], default='BORRADOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='acta',
            name='contenido',
            field=models.TextField(blank=True, default=''),
        ),
    ]
