# Generated by Django 5.2.8 on 2025-11-13 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0005_actaemaillog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='acta',
            old_name='transcripcion_estado',
            new_name='estado_transcripcion',
        ),
        migrations.RemoveField(
            model_name='actaemaillog',
            name='error',
        ),
        migrations.RemoveField(
            model_name='actaemaillog',
            name='ok',
        ),
        migrations.AddField(
            model_name='reunion',
            name='estado',
            field=models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_CURSO', 'En Curso'), ('REALIZADA', 'Realizada')], default='PROGRAMADA', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='actaemaillog',
            name='enviado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
