# Generated by Django 5.2.8 on 2025-11-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0006_rename_transcripcion_estado_acta_estado_transcripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunion',
            name='estado',
            field=models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_CURSO', 'En Curso'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=20, verbose_name='Estado'),
        ),
    ]
