# Generated by Django 5.2.8 on 2025-11-14 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0007_alter_reunion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='archivo_audio',
            field=models.FileField(blank=True, help_text='Archivo de audio (.webm, .ogg) subido por la directiva.', null=True, upload_to='audios_reuniones/'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='contenido',
            field=models.TextField(blank=True, default='Borrador del acta...'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='estado_transcripcion',
            field=models.CharField(choices=[('NO_SUBIDO', 'No Subido'), ('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='NO_SUBIDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='acta',
            name='reunion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acta', to='reuniones.reunion'),
        ),
    ]
