# Generated by Django 5.2.8 on 2025-11-15 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0008_remove_acta_transcripcion_actualizado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acta',
            name='transcripcion_actualizado',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='transcripcion_borrador',
        ),
        migrations.AlterField(
            model_name='acta',
            name='reunion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='acta', serialize=False, to='reuniones.reunion'),
        ),
    ]
