# Generated by Django 5.2.8 on 2025-11-16 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0009_remove_acta_transcripcion_actualizado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogConsultaActa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='reuniones.acta')),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_de_actas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Consulta de Acta',
                'verbose_name_plural': 'Logs de Consultas de Actas',
            },
        ),
    ]
