# Generated by Django 5.2.8 on 2025-11-30 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0010_logconsultaacta'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogTranscripcionActa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_proceso', models.DateTimeField(auto_now_add=True)),
                ('origen', models.CharField(choices=[('ACTA_COMPLETA', 'Acta completa'), ('RESUMEN', 'Resumen'), ('OTRO', 'Otro')], default='ACTA_COMPLETA', max_length=30)),
                ('total_palabras', models.IntegerField(default=0)),
                ('palabras_correctas', models.IntegerField(default=0)),
                ('texto_original', models.TextField(blank=True, null=True)),
                ('texto_transcrito', models.TextField(blank=True, null=True)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_transcripcion', to='reuniones.acta')),
            ],
            options={
                'verbose_name': 'Log de Transcripción de Acta',
                'verbose_name_plural': 'Logs de Transcripciones de Actas',
            },
        ),
    ]
