# Generated by Django 5.2.8 on 2025-12-02 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0011_logtranscripcionacta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogTranscripcionActa',
        ),
    ]
