# Generated by Django 5.2.8 on 2025-12-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0012_delete_logtranscripcionacta'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='contenido_original_ia',
            field=models.TextField(blank=True, help_text='Texto original generado por Vosk. Usado para calcular precisión.', null=True),
        ),
    ]
