# Generated by Django 5.2.8 on 2025-12-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0013_acta_contenido_original_ia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acta',
            name='contenido_original_ia',
        ),
        migrations.AddField(
            model_name='acta',
            name='calificacion_precision',
            field=models.IntegerField(default=0, help_text='Calificación manual de la precisión (0-100) asignada por la directiva.'),
        ),
    ]
