# Generated by Django 5.2.8 on 2025-11-08 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Recurso')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('disponible', models.BooleanField(default=True, help_text='Marcar si el recurso está disponible para ser reservado.')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Inicio de la reserva')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fin de la reserva')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada por Vecino')], default='PENDIENTE', max_length=20)),
                ('motivo', models.TextField(verbose_name='Motivo de la reserva')),
                ('creada_el', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='recursos.recurso')),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_hechas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
