# Generated by Django 5.2.7 on 2025-11-12 02:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0002_solicitudreserva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudreserva',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada por Vecino')], db_index=True, default='PENDIENTE', max_length=10),
        ),
        migrations.AddIndex(
            model_name='solicitudreserva',
            index=models.Index(fields=['solicitante', 'recurso'], name='recursos_so_solicit_4d45df_idx'),
        ),
        migrations.AddConstraint(
            model_name='solicitudreserva',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'PENDIENTE')), fields=('solicitante', 'recurso'), name='uniq_pendiente_por_usuario_y_recurso'),
        ),
    ]
