# Generated by Django 5.2.8 on 2025-12-17 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={},
        ),
        migrations.AddField(
            model_name='comentario',
            name='reply_to_adjunto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='foro.archivoadjunto'),
        ),
        migrations.AlterField(
            model_name='archivoadjunto',
            name='archivo',
            field=models.ImageField(upload_to='archivos/'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
