# Generated by Django 5.2.7 on 2025-11-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0003_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={},
        ),
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=models.TextField(),
        ),
    ]
