# Generated by Django 5.2.7 on 2025-11-04 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0004_alter_comentario_options_alter_comentario_contenido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['fecha_creacion']},
        ),
        migrations.AddField(
            model_name='comentario',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='foro.comentario'),
        ),
    ]
