# Generated by Django 5.2.8 on 2025-11-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0005_alter_comentario_options_comentario_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='visible',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='visible',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
