# Generated by Django 5.2.8 on 2025-11-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0007_archivoadjunto_autor_archivoadjunto_es_mensaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
