# Generated by Django 5.2.8 on 2025-11-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0007_archivoadjunto_autor_archivoadjunto_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivoadjunto',
            name='es_mensaje',
            field=models.BooleanField(default=False, help_text='Si está marcado, se mostrará en la sección de comentarios.'),
        ),
    ]
