# Generated by Django 5.2.8 on 2025-11-22 02:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0008_publicacion_eliminado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comentarios_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
