# Generated by Django 5.2.8 on 2025-11-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0009_comentario_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivoadjunto',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Texto que acompaña a la imagen/audio', null=True),
        ),
    ]
