# Generated by Django 5.2.8 on 2025-11-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0010_archivoadjunto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivoadjunto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
