# Generated by Django 5.2.8 on 2025-11-24 00:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0011_alter_archivoadjunto_descripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='archivoadjunto',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='adjuntos_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
